name: web_client
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Issac <email@example.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  nuts:
    path: ../../../jaguar/nuts
  observable_ish: #1.2.4
    path: ../../../echannel/observable_ish
  data:
    path: ../data

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
